abstract class CubitStates {}
class InitState extends CubitStates{}
class ChangeNavigationBar extends CubitStates{}
class CreateDataBaseState extends CubitStates{}
class InsertIntoDataBase extends CubitStates{}
class UpdateDataBase extends CubitStates{}
class DeleteFromDatabaseState extends CubitStates{}
class ChangeButtonSheetState extends CubitStates{}
class GetDataBaseState extends CubitStates{}
class GetDataBaseLoadingState extends CubitStates{}